#!/usr/bin/env zsh -i

# Auto-generated by Voodoo
# First-time script for project setup (DELETE ME AFTER RUNNING!)

DOCS_DIR=~/dev/githubdocs

print Setting up your virtualenv

rmvirtualenv fw_setup
if [ $? -ne 0 ]; then
    print Removing old virtualenv failed
    exit -1
fi
mkvirtualenv fw_setup
if [ $? -ne 0 ]; then
    print Making fw_setup Virtual env failed
    exit -1
fi

workon fw_setup
if [ $? -ne 0 ]; then
    print Could not switch to fw_setup
    exit -1
fi
print Working in virtualenv fw_setup


# Set up the pip packages
#pip install pytest mock pytest-cov python-coveralls coverage sphinx tox
pip install sphinx
echo "cd ~/dev/fw_setup" >> ~/dev/envs/fw_setup/bin/postactivate

# Start python develop
python setup.py develop

# Initialize the git repo
github_remote='git@github.com:virantha/fw_setup.git'
git init
git remote add origin $github_remote
git add .
git commit -am "Setting up new project fw_setup"

# Prompt if we want to push to remote git
read -q "REPLY?Create remote repository at $github_remote [y/N]?"
if [[  $REPLY == y ]]; then
    curl --data '{"name":"fw_setup", "description":""}' --user "virantha" https://api.github.com/user/repos
fi

read -q "REPLY?Push to remote repository $github_remote [y/N]?"
if [[  $REPLY == y ]]; then
    git push -u origin master
fi

print
# Create the docs repository
current_dir=`pwd`
read -q "REPLY?Create and push docs to $github_remote [y/N]?"
if [[  $REPLY == y ]]; then
    # Go to the docs build dir, and check out our repo
    cd $DOCS_DIR
    git clone https://github.com/virantha/fw_setup.git
    cd fw_setup
    git checkout --orphan gh-pages
    git rm -rf .

    cd $current_dir/docs
    pip install sphinx
    make html
    cd $DOCS_DIR
    cd fw_setup
    touch .nojekyll
    git add .
    git commit -m "docs"
    git push origin gh-pages

fi